export const ListingData = {
  "status_code": 200,
  "message": "success",
  "data" : [
    {
      "id": 1,
      "name": "오다커피",
      "product": "아이스 아메리카노, 아인슈페너, 바닐라 라뗴 ...",
      "rating": 4.5,
      "review_cnt": 20,
      "is_ts": true,
      "is_pn": true,
      "image": null,
	  },
	  {
      "id": 2,
      "name": "세훈빵집",
      "product":  "아이스 아메리카노, 아인슈페너, 바닐라 라뗴 ...",
      "rating": 4.5,
      "review_cnt": 20,
      "is_ts": true,
      "is_pn": false,
      "image": null,
	  },
    {
      "id": 3,
      "name": "세훈빵집",
      "product":  "아이스 아메리카노, 아인슈페너, 바닐라 라뗴 ...",
      "rating": 4.5,
      "review_cnt": 20,
      "is_ts": false,
      "is_pn": true,
      "image": null,
	  },
    {
      "id": 4,
      "name": "세훈빵집",
      "product":  "아이스 아메리카노, 아인슈페너, 바닐라 라뗴 ...",
      "rating": 4.5,
      "review_cnt": 20,
      "is_ts": true,
      "is_pn": true,
      "image": null,
	  },
    {
      "id": 5,
      "name": "세훈빵집",
      "product":  "아이스 아메리카노, 아인슈페너, 바닐라 라뗴 ...",
      "rating": 4.5,
      "review_cnt": 20,
      "is_ts": false,
      "is_pn": false,
      "image": null,
	  },
    {
      "id": 6,
      "name": "세훈빵집",
      "product":  "아이스 아메리카노, 아인슈페너, 바닐라 라뗴 ...",
      "rating": 4.5,
      "review_cnt": 20,
      "is_ts": true,
      "is_pn": true,
      "image": null,
	  },
    {
      "id": 7,
      "name": "세훈빵집",
      "product":  "아이스 아메리카노, 아인슈페너, 바닐라 라뗴 ...",
      "rating": 4.5,
      "review_cnt": 20,
      "is_ts": true,
      "is_pn": true,
      "image": null,
	  },
    {
      "id": 8,
      "name": "세훈빵집",
      "product":  "아이스 아메리카노, 아인슈페너, 바닐라 라뗴 ...",
      "rating": 4.5,
      "review_cnt": 20,
      "is_ts": true,
      "is_pn": true,
      "image": null,
	  },
    {
      "id": 9,
      "name": "세훈빵집",
      "product":  "아이스 아메리카노, 아인슈페너, 바닐라 라뗴 ...",
      "rating": 4.5,
      "review_cnt": 20,
      "is_ts": true,
      "is_pn": true,
      "image": null,
	  },
    {
      "id": 10,
      "name": "세훈빵집",
      "product":  "아이스 아메리카노, 아인슈페너, 바닐라 라뗴 ...",
      "rating": 4.5,
      "review_cnt": 20,
      "is_ts": true,
      "is_pn": true,
      "image": null,
	  },
  ]
}
